--- # Install Node.js, GIT, NFS and Shopping-List-App
- hosts: all
  vars_files:
    - ./group_vars/shopping-list-ini-items.yml
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Read installation instructions for NodeJS 14
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - name: Install NodeJS (NPM installs as well)
      apt:
        name: nodejs
        state: latest
    - name: Install GIT
      apt:
        name: git
        state: latest
    - name: Install NFS
      apt:
        name: nfs-kernel-server
        state: latest
    - name: Install SQLite 3
      apt:
        name: sqlite3
        state: latest
    - name: Clone app repository
      git:
        repo: https://github.com/cuevae/shopping-list-app.git
        dest: /var/www/shopping-list-app
    - name: Install NPM dependencies based on package.json file created above
      npm:
        path: /var/www/shopping-list-app
    - name: Fill in sqlite template with initial shopping list items
      template:
        src: shopping-list-ini.sql.j2
        dest: /var/www/shopping-list-app/shopping-list-ini.sql
    - name: Create starting sqlite database
      shell: cd /var/www/shopping-list-app && sqlite3 sla-db.sqlt < shopping-list-ini.sql && rm -f shopping-list-ini.sql