--- 
# Application host provisioning (NodeJS, GIT, App repository, Install NPM dependencies)
- hosts: sla-host
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Read installation instructions for NodeJS 14
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - name: Install NodeJS (NPM installs as well)
      apt:
        name: nodejs
        state: latest
    - name: Install GIT
      apt:
        name: git
        state: latest
    - name: Clone app repository
      git:
        repo: https://github.com/cuevae/shopping-list-rn-expo.git
        dest: /vagrant/shopping-list-app
    - name: Check if node_modules symlink exists
      stat:
        path: /vagrant/shopping-list-app/node_modules
      register: node_modules_symlink
    - name: Delete node_modules symlink if exists
      file:
        path: /vagrant/shopping-list-app/node_modules
        state: absent
      when: node_modules_symlink.stat.exists
    - name: Check if node_modules folder exists
      stat:
        path: /home/vagrant/node_modules
      register: node_modules_folder
    - name: Delete node_modules folder if exists
      file:
        path: /home/vagrant/node_modules
        state: absent
      when: node_modules_folder.stat.exists
    - name: Create node_modules folder
      file:
        path: /home/vagrant/node_modules
        owner: vagrant
        group: vagrant
        mode: '0755'
        state: directory
    - name: Symlink node_modules folder
      file: 
        src: /home/vagrant/node_modules
        dest: /vagrant/shopping-list-app/node_modules
        owner: vagrant
        group: vagrant
        state: link
    - name: Install NPM dependencies based on package.json from SLA repository
      npm:
        path: /vagrant/shopping-list-app
# DB hosts provisioning
- hosts: db-host
  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: latest
    - name: Bring db initialization template
      template:
        src: psql-sla-db-init.sql.j2
        dest: /tmp/psql-sla-db-init.sql
    - name: Initialize DB
      shell:
        cmd: 'sudo -u postgres createdb sla_db && sudo -u postgres psql sla_db < /tmp/psql-sla-db-init.sql'
    #- name: Remove initialization template
    #  file:
    #    state: absent
    #    path: /tmp/psql-sla-db-init.sql
    - name: Download and unTAR Postgrest to /usr/local/bin
      unarchive:
        src: https://github.com/PostgREST/postgrest/releases/download/v7.0.1/postgrest-v7.0.1-linux-x64-static.tar.xz
        dest: /usr/local/bin
        remote_src: yes
    - name: Make PostgREST configuration file available
      template:
        src: postgREST-sladb-conn.conf.j2
        dest: /home/vagrant/postgREST-sladb-conn.conf
    - name: Create file to collect PostgREST connection logs
      file:
        path: /tmp/postgrest.log
        state: touch
        mode: '0766'
    - name: Start PostgREST to run in the background
      shell:
        cmd: 'nohup postgrest /home/vagrant/postgREST-sladb-conn.conf </dev/null >/tmp/postgrest.log 2>&1 &'