--- # Install Node.js, GIT, NFS and Shopping-List-App
- hosts: all
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Read installation instructions for NodeJS 14
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - name: Install NodeJS (NPM installs as well)
      apt:
        name: nodejs
        state: latest
    - name: Install GIT
      apt:
        name: git
        state: latest
    - name: Install NFS
      apt:
        name: nfs-kernel-server
        state: latest
    - name: Clone app repository
      git:
        repo: https://github.com/cuevae/shopping-list-app.git
        dest: /var/www/shopping-list-app
    - name: Install NPM dependencies based on package.json file created above
      npm:
        path: /var/www/shopping-list-app