--- # Install Node.js, GIT, NFS and Shopping-List-App
- hosts: all
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Read installation instructions for NodeJS 14
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - name: Install NodeJS (NPM installs as well)
      apt:
        name: nodejs
        state: latest
    - name: Install GIT
      apt:
        name: git
        state: latest
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: latest
    - name: Clone app repository
      git:
        repo: https://github.com/cuevae/shopping-list-rn-expo.git
        dest: /vagrant/shopping-list-app
    - name: Symlink node_modules
    #Otherwise vagrant synced folder fails with NPM (see https://stackoverflow.com/questions/41601417/vagrant-filesystem-issues-with-npm)
      shell:
        cmd: 'mkdir /home/vagrant/node_modules && ln -sf /home/vagrant/node_modules /vagrant/shopping-list-app/'
    - name: Install NPM dependencies based on package.json from the repository above
      npm:
        path: /vagrant/shopping-list-app