--- 
# Application host provisioning (NodeJS, GIT, App repository, Install NPM dependencies)
- hosts: sla-host
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Read installation instructions for NodeJS 14
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - name: Install NodeJS (NPM installs as well)
      apt:
        name: nodejs
        state: latest
    - name: Install GIT
      apt:
        name: git
        state: latest
    - name: Clone app repository
      git:
        repo: https://github.com/cuevae/shopping-list-rn-expo.git
        dest: /vagrant/shopping-list-app
        force: yes
    - name: Install Yarn globally
      npm:
        name: yarn
        global: yes
    - name: Install Expo-CLI globally
      npm:
        name: expo-cli
        global: yes
    - name: User Yarn to install dependencies
      yarn:
        path : /vagrant/shopping-list-app
    - name: Set environment variable for Expo with the sla-host local ip
      lineinfile:
        path: /etc/environment
        line: REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.129
    - name: Increase number of files watched so remote sync can work without issues
      shell:
        cmd: 'echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p'
# DB hosts provisioning
- hosts: db-host
  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: latest
    - name: Bring db initialization template
      template:
        src: psql-sla-db-init.sql.j2
        dest: /tmp/psql-sla-db-init.sql
    - name: Create file to collect PostgreSQL logs
      file:
        path: /tmp/pg.log
        state: touch
        mode: '0766'
    - name: Initialize DB
      shell:
        cmd: 'sudo -u postgres createdb sla_db > /tmp/pg.log 2>&1 && sudo -u postgres psql sla_db < /tmp/psql-sla-db-init.sql > /tmp/pg.log 2>&1'
    - name: Remove initialization template
      file:
        state: absent
        path: /tmp/psql-sla-db-init.sql
    - name: Download and unTAR Postgrest to /usr/local/bin
      unarchive:
        src: https://github.com/PostgREST/postgrest/releases/download/v7.0.1/postgrest-v7.0.1-linux-x64-static.tar.xz
        dest: /usr/local/bin
        remote_src: yes
    - name: Make PostgREST configuration file available
      template:
        src: postgREST-sladb-conn.conf.j2
        dest: /home/vagrant/postgREST-sladb-conn.conf
    - name: Start PostgREST to run in the background
      shell:
        cmd: 'nohup postgrest /home/vagrant/postgREST-sladb-conn.conf </dev/null >/tmp/postgrest.log 2>&1 &'